# Format and labels used aim to match those used by Ansible project
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Major Changes'
    labels:
      - 'major'
  - title: 'Minor Changes'
    labels:
      - 'feature'
      - 'minor'
      - 'enhancement'
      - 'refactoring'
  - title: 'Bugfixes and other small Improvements'
    labels:
      - 'bug'
      - 'patch'
  - title: 'Deprecations'
    labels:
      - 'deprecated'
change-template: '- $TITLE #$URL (@$AUTHOR)'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
      - 'refactoring'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'deprecated'
  default: patch
autolabeler:
  - label: 'skip-changelog'
    title: '/chore/i'
  - label: 'bug'
    title: '/fix/i'
  - label: 'enhancement'
    title: '/(enhance|improve)/i'
  - label: 'feature'
    title: '/feature/i'
  - label: 'dreprecated'
    title: '/deprecat/i'
template: |
  $CHANGES
