---
name: New release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: create release draft
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install antsibull-changelog
        run: python -m pip install antsibull-changelog --disable-pip-version-check

      - name: Install the reqs of antsi-change-pr-getter
        run: python -m pip install -r requirements-antsi.txt

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: calculate next version
        id: version
        uses: patrickjahns/version-drafter-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate new version in changelog.yaml
        run: antsibull-changelog release -v --version "${{ steps.previoustag.outputs.tag }}"

      - name: Generate changelog.yaml
        run: python antsi_change_pr_getter.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SINCE_VERSION: "${{ steps.previoustag.outputs.tag }}"
          GITHUB_REPOSITORY: "T-Systems-MMS/ansible-collection-acme"

      - name: Update Changelog.rst
        run: antsibull-changelog generate

      - name: push changelog
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'update changelog'
          force-add: 'true'
          files: CHANGELOG.rst
          name: T-Systems MMS
          email: frage@t-systems-mms.com

      # do a second checkout to prevent race situation
      # changelog gets updated but action works on old commit id
      - uses: actions/checkout@v2.3.4
        with:
          ref: master

      - name: Generate changelog for the release
        run: |
          sed '/v${{ steps.previoustag.outputs.tag }}/Q' CHANGELOG.rst > CHANGELOGRELEASE.rst

      - name: Read CHANGELOG.md
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./CHANGELOGRELEASE.rst

      - name: Create Release draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This token is provided by Actions, you do not need to create your own token
        with:
          release_name: ${{ steps.version.outputs.next-version }}
          tag_name: ${{ steps.version.outputs.next-version }}
          body: |
            ${{ steps.package.outputs.content }}
          draft: true
